Resources:
  ContractTestSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Superuser credentials for the Redshift cluster
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"''@/\ ,'

  # EndpointAccess Contract Tests dependencies.
  RedshiftEndpointAccessContractCluster:
    Type: AWS::Redshift::Cluster
    DependsOn:
      - ContractTestSecret
      - RedshiftEndpointAccessContractClusterSubnetGroup
      - RedshiftEndpointAccessVpcContractSecurityGroup
      - RedshiftEndpointAccessVpcContractSecurityGroup1
    Properties:
      ClusterType: multi-node
      NodeType: ra3.4xlarge
      NumberOfNodes: 2
      DBName: dev
      MasterUsername: !Join [ '', [ '{{resolve:secretsmanager:', !Ref ContractTestSecret, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref ContractTestSecret, ':SecretString:password}}' ] ]
      AvailabilityZoneRelocation: true
      PubliclyAccessible: false
      Encrypted: true

  RedshiftEndpointAccessContractVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.2.0.0/16

  RedshiftEndpointAccessContractSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.2.1.0/24
      VpcId: !Ref RedshiftEndpointAccessContractVpc
      AvailabilityZone:
        Fn::Select:
          - '0'
          - Fn::GetAZs:
              Ref: AWS::Region
  RedshiftEndpointAccessContractClusterSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: EndpointAccess Contract Cluster Subnet Group.
      SubnetIds: [ !Ref RedshiftEndpointAccessContractSubnet ]

  RedshiftEndpointAccessVpcContractSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EndpointAccess Contract Security Group.
      VpcId: !Ref RedshiftEndpointAccessContractVpc

  RedshiftEndpointAccessVpcContractSecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EndpointAccess Contract Security Group 1.
      VpcId: !Ref RedshiftEndpointAccessContractVpc

Outputs:
  RedshiftEndpointAccessContractResourceOwnerId:
    Value: !Ref AWS::AccountId
    Export:
      Name: RedshiftEndpointAccessContractResourceOwner

  RedshiftEndpointAccessContractClusterId:
    Value: !Ref RedshiftEndpointAccessContractCluster
    Export:
      Name: RedshiftEndpointAccessContractCluster

  RedshiftEndpointAccessContractClusterSubnetGroupName:
    Value: !Ref RedshiftEndpointAccessContractClusterSubnetGroup
    Export:
      Name: RedshiftEndpointAccessContractClusterSubnetGroup

  RedshiftEndpointAccessVpcContractSecurityGroupName:
    Value: !Ref RedshiftEndpointAccessVpcContractSecurityGroup
    Export:
      Name: RedshiftEndpointAccessVpcContractSecurityGroup

  RedshiftEndpointAccessVpcContractSecurityGroup1Name:
    Value: !Ref RedshiftEndpointAccessVpcContractSecurityGroup1
    Export:
      Name: RedshiftEndpointAccessVpcContractSecurityGroup1
