AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
              StringLike:
                aws:SourceArn:
                  Fn::Sub: arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/resource/AWS-Redshift-Cluster/*
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "cloudwatch:PutMetricData"
                - "ec2:AssociateAddress"
                - "ec2:CreateNetworkInterface"
                - "ec2:CreateVpcEndpoint"
                - "ec2:DeleteNetworkInterface"
                - "ec2:DeleteVpcEndpoints"
                - "ec2:DescribeAddresses"
                - "ec2:DescribeNetworkInterfaces"
                - "ec2:DescribeSubnets"
                - "ec2:DescribeVpcEndpoints"
                - "ec2:DescribeVpcs"
                - "ec2:DisassociateAddress"
                - "ec2:ModifyNetworkInterfaceAttribute"
                - "ec2:ModifyVpcEndpoint"
                - "iam:CreateServiceLinkedRole"
                - "redshift:CreateCluster"
                - "redshift:CreateTags"
                - "redshift:DeleteCluster"
                - "redshift:DeleteResourcePolicy"
                - "redshift:DeleteTags"
                - "redshift:DescribeClusterDbRevisions"
                - "redshift:DescribeClusters"
                - "redshift:DescribeLoggingStatus"
                - "redshift:DescribeSnapshotCopyGrant"
                - "redshift:DescribeTags"
                - "redshift:DisableLogging"
                - "redshift:DisableSnapshotCopy"
                - "redshift:EnableLogging"
                - "redshift:EnableSnapshotCopy"
                - "redshift:FailoverPrimaryCompute"
                - "redshift:GetResourcePolicy"
                - "redshift:ModifyAquaConfiguration"
                - "redshift:ModifyCluster"
                - "redshift:ModifyClusterDbRevisions"
                - "redshift:ModifyClusterIamRoles"
                - "redshift:ModifyClusterMaintenance"
                - "redshift:ModifySnapshotCopyRetentionPeriod"
                - "redshift:PauseCluster"
                - "redshift:PutResourcePolicy"
                - "redshift:RebootCluster"
                - "redshift:ResizeCluster"
                - "redshift:RestoreFromClusterSnapshot"
                - "redshift:ResumeCluster"
                - "redshift:RotateEncryptionKey"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
