AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "redshift:CreateCluster"
                - "redshift:CreateTags"
                - "redshift:DeleteCluster"
                - "redshift:DeleteTags"
                - "redshift:DescribeClusterDbRevisions"
                - "redshift:DescribeClusters"
                - "redshift:DescribeLoggingStatus"
                - "redshift:DescribeSnapshotCopyGrant"
                - "redshift:DisableLogging"
                - "redshift:DisableSnapshotCopy"
                - "redshift:EnableLogging"
                - "redshift:EnableSnapshotCopy"
                - "redshift:ModifyAquaConfiguration"
                - "redshift:ModifyCluster"
                - "redshift:ModifyClusterDbRevisions"
                - "redshift:ModifyClusterIamRoles"
                - "redshift:ModifyClusterMaintenance"
                - "redshift:ModifySnapshotCopyRetentionPeriod"
                - "redshift:PauseCluster"
                - "redshift:RebootCluster"
                - "redshift:ResizeCluster"
                - "redshift:RestoreFromClusterSnapshot"
                - "redshift:ResumeCluster"
                - "redshift:RotateEncryptionKey"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
