Resources:
  RedshiftScheduledActionContractRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.redshift.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                  - "redshift:CreateScheduledAction"
                  - "redshift:DeleteScheduledAction"
                  - "redshift:DescribeScheduledActions"
                  - "redshift:ModifyScheduledAction"
                  - "redshift:PauseCluster"
                  - "redshift:ResizeCluster"
                  - "redshift:ResumeCluster"
                Resource: "*"

Outputs:
  RedshiftScheduledActionContractRoleArn:
    Value: !GetAtt RedshiftScheduledActionContractRole.Arn
    Export:
      Name: RedshiftScheduledActionContractRole
